First branch
ReemMohamedAbdelfatah/Hello-Microverse pull request #4
Opened 2022-08-16 15:27 UTC by ReemMohamedAbdelfatah

2022-08-16 15:53 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @ReemMohamedAbdelfatah :wave:

### Highlights :1st_place_medal:
 
:heavy_check_mark: Meaningful commits
:heavy_check_mark: Added .gitignore

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional Suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. Otherwise reach out to me on slack which is more fast. You can reach out to me on slack by searching my name in **full-time-students** channel :+1:

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 15:53 UTC, HAMMAS-SALEEM commented on Style.css
> +
## 1. 
![pr-title](https://user-images.githubusercontent.com/93039359/184921057-3f1452ce-008b-4b49-bf3a-b3ff858cdfe6.png)

- [ ] Your PR has a title that is not so descriptive enough. Because **First branch** is not describing what are you doing in the project. PR title fully describes what is happening in this branch. You could use **Setup Hello Microverse Project** for your PR title. :+1:

2022-08-16 15:53 UTC, HAMMAS-SALEEM commented on Style.css
> +
## 2
### Your Summary
![pr-summary](https://user-images.githubusercontent.com/93039359/184921201-34f5fea5-f910-4134-b228-0fa9ec7a98e0.png)

### Descriptive Summary Example :heavy_check_mark:
![descriptive-summary](https://user-images.githubusercontent.com/93039359/184921477-5686f05d-45cf-4d90-8522-6db2f012e302.png)

- [ ] You don't have a summary for your project. You can see the image above to get an idea of what a descriptive summary looks like. The summary tells in detail what are you doing in this pull request and why. :thinking:

2022-08-16 15:53 UTC, HAMMAS-SALEEM commented on Style.css
> +
## 3.
![pr-title (copy)](https://user-images.githubusercontent.com/93039359/184921868-a1fc321c-6a68-4454-b526-12bcf1d7a159.png)

- [ ] Your branch name is not descriptive enough. You are using **First branch**, you can use  **feature/setup-hello-microverse** or **feature/initialize-hello-microverse** :+1:

2022-08-16 15:53 UTC, HAMMAS-SALEEM commented on Style.css
> +
## 4.
### Your Linters
![linters-not-passing (copy)](https://user-images.githubusercontent.com/93039359/184922292-bea79490-5218-43ed-b74b-4cdcdd88dfed.png)


- [ ] Your linters are not passing all the tests. :cry: Please fix stylint errors from your code. These errors can break your application so please take them seriously :relaxed:

2022-08-16 15:53 UTC, HAMMAS-SALEEM commented on Style.css
> +
## 5.
### Your Readme
![readme](https://user-images.githubusercontent.com/93039359/184922539-651673d7-2a3e-4c22-806c-66261733105b.png)

- [ ] Your readme is not very descriptive. Please add readme file using this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) :blush: Your readme file is the documentation of your project so please take it seriously :+1:
- [ ] You didn't add an license (MIT) for you project. Please add it using this [template](https://github.com/microverseinc/readme-template/blob/master/MIT.md) :blush:

2022-08-16 15:53 UTC, HAMMAS-SALEEM commented on Style.css
> +
## 6.
### Your test.md file
![test (copy)](https://user-images.githubusercontent.com/93039359/184923342-74f72f78-b467-438e-a074-04d5bf4577f4.png)

- [ ] You have added your test.md file in .gitignore but it is still in your Github Repository. Please fix this issue why your .gitignore is not working :+1:

2022-08-16 17:33 UTC, BertrandConxy requested changes
Hi @ReemMohamedAbdelfatah , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- Good README
- no linter errors


 ## Required Changes ♻️

- [ ] Good job so far 👏. I realized that you may be facing the same problem as other new Micronauts of not knowing where to find some options here on GitHub because from my observations, as the previous reviewers suggested, It would be better if you correct your PR title, add the PR description and adjusting the branch name to be more meaningful. 
**For changing the PR Title**
![image](https://user-images.githubusercontent.com/90222110/184940872-edbadc82-7ceb-4d98-b6cb-ca0e83012393.png)
Click on the edit button on the right side in the Pull request tap and by there you can be able to change the PR title as suggested by the previous reviewer 😉

**For adding PR description**
![image](https://user-images.githubusercontent.com/90222110/184941267-e6e23ba0-7e57-4ecb-af22-ef88eba0c48d.png)
All you need to do is to edit that first comment box by clicking on the 3 dots as shown in the picture above and then click edit. Then, you can add a brief description of what you have done

**For editing branch name**
![image](https://user-images.githubusercontent.com/90222110/184941971-3847bb6c-002c-422d-babc-5690a712f748.png)
You will see all your branches and by there you can be able to rename one 😉 

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 17:33 UTC, BertrandConxy commented on test.md
> +This file should be ignored by git
- [ ] From my observation, I can see that this file is still visible on Github despite being put in the `.gitignore` That may be because you have pushed it before on Github. The fix is that you may delete it manually on Github and then make sure that locally in your Editor(eg Visual code) it is marked as untracked by git. By that, you are sure that when you push your code, it will not be visible on Github.

2022-08-16 19:29 UTC, ReemMohamedAbdelfatah commented on test.md
> +This file should be ignored by git
Yes Git doesn't recognize this file anymore.

2022-08-16 19:31 UTC, ReemMohamedAbdelfatah commented on test.md
> +This file should be ignored by git
should I do commit again?

2022-08-16 19:38 UTC, ReemMohamedAbdelfatah commented on test.md
> +This file should be ignored by git
@BertrandConxy Am I ready to submit the project now?

2022-08-17 04:14 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @ReemMohamedAbdelfatah 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job implementing the requirements by the previous reviewers 💯✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
- No linter errors ✅
- Good summary description ✅


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 04:14 UTC, Bondok6 commented on README.md
>  This project is MIT licensed.
- [OPTIONAL] I suggest adding the `MIT.md` file to your project 👌, Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it 😉

> The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯

2022-08-17 04:14 UTC, Bondok6 commented on Style.css
> +}
- [OPTIONAL] Great job here 👌💯 but according to the requirements, you should use a class to select the `<h1>` tag, Kindly add a class name to in `<h1 class="anyname">` tag and use it in your CSS file 👌

![image](https://user-images.githubusercontent.com/45231276/185032956-ca65df88-2c93-4fdc-97c0-93e7050d2989.png)

2022-08-17 12:10 UTC, merged